#!/bin/bash
#
defaultHMCUser="hmc"				# default user
defaultSetup="i"					# default install=i, u=update
defaultPath="/usr/local/bin/hmc"	# default installation path


if [ $EUID -ne 0 ]; then
	echo "This script must be run as root"
	exit 1
fi
###
# install or setup
###
while true; do
	read -p "insatll or update i/u($defaultSetup):" setupType
	if [ "$setupType" == "i" ]; then
		echo "setup type is install"
		break
	fi
	if [ "$setupType" == "u" ]; then
		echo "setup type is update"
		break
	fi
done

###
# path for installation
###
read -p "path of installation ($defaultPath):" pathHMC
if [ -z "$pathHMC" ]; then
	hmcUser=$defaultPath
fi

###
# set  mask log
###
#chmod g+w
#chmod g+s 
#umask 0002 



####
#HMC User and password
####
read -p "Enter the User Name under the script is running($defaultHMCUser):" hmcUser
echo ""
if [ -z "$hmcUser" ]; then
	hmcUser=$defaultHMCUser
fi
while true ;do
	read -sp "Enter  the Password of the User $hmcUser:" hmcPassword1
	echo ""
	read -sp "REnter the Password of the User $hmcUser:" hmcPassword2
	echo ""
	if [ "$hmcPassword1" == "$hmcPassword2" ]; then
		break
	fi
	echo "passwords do not match, try again"
done





